name: CodeIgniter

on:
  push:
    # branches: [ "master" ]
  pull_request:
    # branches: [ "master" ]
  release:
    types: [published]
  workflow_dispatch: # to run manually

permissions:
  contents: read

jobs:
  codeigniter-test:
    environment: unit_test
    runs-on: ubuntu-latest
    services:
      db:
        image: mariadb
        env:
          MYSQL_DATABASE: ci4_test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mariadb-admin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md


    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        database.tests.hostname: 127.0.0.1
        database.tests.database: ci4_test
        database.tests.username: root
        database.tests.password: root
        database.tests.DBDriver: MySQLi
        database.tests.port: 3306
        database.tests.DBPrefix:  
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        GRAPH_USER_SCOPES: ${{ secrets.GRAPH_USER_SCOPES }}
        REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
      run: vendor/bin/phpunit
